version: '3.8'
services:
  hm-fe:  #前端项目的service name
    container_name: 'hm-fe-container'  #容器名称
    image: nginx  #指定镜像
    restart: always
    ports:
    - 8080:80
    volumes: 
    - ./nginx.conf:/etc/nginx/nginx.conf  #挂载nginx配置
    - ./build:/usr/share/nginx/html/    #挂载项目
    depends_on:
    - hm-se
  hm-se:    #后端项目的service name
    container_name: 'hm-se-container'
    build: ./node  #根据server目录下面的Dockerfile构建镜像
    restart: always
    expose:
    - 3002

